"""Add EvaluationCriterion

Revision ID: 25739a51aeb0
Revises: d6433dc943ad
Create Date: 2026-06-16 19:46:38.872140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25739a51aeb0'
down_revision: Union[str, Sequence[str], None] = 'd6433dc943ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_outcome_id', sa.Integer(), nullable=True),
    sa.Column('ce_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['learning_outcome_id'], ['learning_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_criteria_id'), 'evaluation_criteria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_criteria_id'), table_name='evaluation_criteria')
    op.drop_table('evaluation_criteria')
    # ### end Alembic commands ###
