"""Add curso to Module

Revision ID: 86ee1317b86a
Revises: 25739a51aeb0
Create Date: 2026-06-16 19:54:30.781187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ee1317b86a'
down_revision: Union[str, Sequence[str], None] = '25739a51aeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('curso', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'curso')
    # ### end Alembic commands ###
